#!/usr/bin/env python3
"""Generate bq/01_config.sql from conf/*.json.

The BigQuery path needs the lexicon, codeframe, question roles and prose rubrics
as TABLES, not as files on someone's laptop. This keeps the two paths from
drifting: edit the JSON, re-run this, commit the SQL.

Patterns must be RE2-safe (BigQuery's regex engine): no lookahead, no
lookbehind, no backreferences. This script rejects any pattern that uses them
rather than letting it fail at query time.

  python3 tools/gen_bq_config.py > bq/01_config.sql
"""
from __future__ import annotations

import json
import re
import sys

RE2_UNSAFE = re.compile(r"\(\?[=!<]|\\[1-9]")


def q(s):
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ") + "'"


def check(pattern, where):
    if RE2_UNSAFE.search(pattern):
        sys.exit(f"FAIL: {where} uses a construct RE2 does not support: {pattern}")
    return pattern


def main():
    lex = json.load(open("conf/scale_lexicon.json"))
    cf = json.load(open("conf/codeframe.json"))
    roles = json.load(open("conf/question_roles.json"))["roles"]
    rub = json.load(open("conf/prose_rubrics.json"))

    out = ['-- GENERATED by tools/gen_bq_config.py from conf/*.json -- do not hand-edit.',
           '-- Regenerate after editing any conf file, and commit both.',
           '--',
           '-- These four tables are the analysis contract. Every judgement the pipeline',
           '-- makes about what an answer MEANS is in here, in rows you can read, diff',
           '-- and version -- not buried in a CASE expression.',
           '',
           'DECLARE ds STRING DEFAULT "PROJECT_ID.abr_00_config";',
           '']

    # scale lexicon
    rows = ",\n".join(f"  ({q(p.lower())}, {float(s)})"
                      for p, s in sorted(lex["intensity"].items(), key=lambda kv: -len(kv[0])))
    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.scale_intensity` AS',
            '-- Higher score = more of what the question asks about, NOT more favourable.',
            '-- Favourability is derived by combining this with construct polarity,',
            '-- because "A lot" is the best answer to "did you like it" and the worst',
            '-- answer to "was it boring". Longest phrase wins at match time.',
            'SELECT * FROM UNNEST([STRUCT<phrase STRING, intensity FLOAT64>',
            rows, ']);', '']

    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.scale_sentinel` AS',
            '-- Outside the ordered scale. Excluded from every box, the mean, and the',
            '-- scale length. These sit at different codes in different questions and',
            '-- sometimes mid-scale, so they can only be identified by label.',
            'SELECT * FROM UNNEST([',
            ",\n".join(f"  {q(s.lower())}" for s in lex["sentinel"]),
            ']) AS phrase;', '']

    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.construct_polarity` AS',
            '-- A question about something undesirable inverts favourability.',
            'SELECT * FROM UNNEST([STRUCT<pattern STRING, polarity STRING>',
            ",\n".join(f"  ({q(p.lower())}, 'negative')" for p in lex["negative_constructs"]) + "," ,
            ",\n".join(f"  ({q(p.lower())}, 'mid_optimal')" for p in lex["mid_optimal_constructs"]),
            ']);', '']

    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.nominal_meta` AS',
            '-- Pick lists, not scales. Reported as option shares; forcing a rank onto',
            '-- "who would you watch with" invents a scale the questionnaire never asked.',
            'SELECT * FROM UNNEST([',
            ",\n".join(f"  {q(m)}" for m in sorted(lex["nominal_metas"])),
            ']) AS meta;', '']

    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.behavioural_stem` AS',
            '-- Ordinal, but a cut rather than a verdict on the film. Ranking these is',
            '-- fine; publishing a "top box" on religious attendance is not.',
            'SELECT * FROM UNNEST([',
            ",\n".join(f"  {q(s.lower())}" for s in lex.get("behavioural_stems", [])),
            ']) AS stem;', '']

    # codeframe
    trows = []
    for t in cf["themes"]:
        for p in t["patterns"]:
            check(p, f"codeframe {t['id']}")
            trows.append(f"  ({q(t['id'])}, {q(t['label'])}, {q(t['polarity'])}, {q(p.lower())})")
    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.codeframe` AS',
            '-- A codeframe is a hypothesis. 06_themes.sql also clusters with no',
            '-- codeframe at all and reports what this frame fails to cover.',
            'SELECT * FROM UNNEST([STRUCT<theme_id STRING, theme_label STRING, '
            'theme_polarity STRING, pattern STRING>',
            ",\n".join(trows), ']);', '']

    # roles
    rrows = []
    for role, metas in roles.items():
        for m in metas:
            rrows.append(f"  ({q(role)}, {q(m)})")
    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.question_role` AS',
            '-- Theme incidence is only meaningful inside a question context.',
            '-- "Mentioned anywhere across 20 open ends" is ~100% for every theme.',
            'SELECT * FROM UNNEST([STRUCT<role STRING, meta STRING>',
            ",\n".join(rrows), ']);', '']

    # prose rubric
    prows = []
    for fam, spec in rub["families"].items():
        for m in spec["metrics"]:
            prows.append(f"  ({q(fam)}, {q(m)})")
    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.prose_metric` AS',
            'SELECT * FROM UNNEST([STRUCT<family STRING, meta STRING>',
            ",\n".join(prows), ']);', '']
    crows = []
    for fam, spec in rub["families"].items():
        for c in spec["cues"]:
            check(c["rx"], f"rubric {fam}")
            crows.append(f"  ({q(fam)}, {q(c['rx'].lower())}, {int(c['score'])})")
    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.prose_cue` AS',
            '-- The most extreme cue in a sentence wins; a negation just before it flips',
            '-- the score. Coverage and confidence are reported, never assumed.',
            'SELECT * FROM UNNEST([STRUCT<family STRING, pattern STRING, score INT64>',
            ",\n".join(crows), ']);', '']
    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.prose_negation` AS',
            'SELECT * FROM UNNEST([',
            ",\n".join(f"  {q(n.lower())}" for n in rub["negations"]),
            ']) AS token;', '']
    out += ['CREATE OR REPLACE TABLE `PROJECT_ID.abr_00_config.prose_not_applicable` AS',
            '-- A persona writing "N/A - I am a parent" is correcting a base the harness',
            '-- got wrong, not failing to answer. Counted separately from unscored.',
            f'SELECT {q(rub["not_applicable"].lower())} AS pattern;', '']

    print("\n".join(out))


if __name__ == "__main__":
    main()
