#!/usr/bin/env python3
"""
Generate the wide-to-long UNPIVOT DDL for the three READ section families.

Each raw row carries N repeating 7-column question blocks
(Q{n}_question, Q{n}_meta, Q{n}_type, Q{n}_rating_label, Q{n}_rating,
Q{n}_selected, Q{n}_qual). This turns one row of 291 columns into 35 rows of a
narrow table, which is what makes the data queryable: "top box on POSTINT"
stops meaning "know that POSTINT is Q29 in section 2.2 but Q7 in section 2.3"
and becomes WHERE meta = 'POSTINT'.

Why UNPIVOT and not a JSON trick: JSON_VALUE requires a literal path, so you
cannot loop '$.Q' || i || '_question'. Multi-column UNPIVOT is the only clean
native option.

Note `q_idx` is positional within a file, NOT a stable question id. Q1 in
section 2.2 is a different question from Q1 in section 2.3. Stable identity is
(meta, question_text), hashed into question_key in sql/11_stg_response.sql.

Usage
-----
    python3 tools/gen_unpivot.py s22          # print DDL for one family
    python3 tools/gen_unpivot.py --all        # write all three to sql/

Generated SQL carries ${PROJECT_ID}, ${DS_RAW} and ${DS_STG} placeholders;
tools/shape_staging.sh substitutes them from config.env at run time.
"""

import os
import sys

# family -> (section code, question count, expected staged row count)
FAMILIES = {
    "s21": ("2.1", 20, 11920),   # 596 rows x 20 questions
    "s22": ("2.2", 35, 13930),   # 398 rows x 35 questions
    "s23": ("2.3", 36, 14328),   # 398 rows x 36 questions
    "s14": ("1.4",  4,  1592),   # 398 rows x  4 questions
}

FIELDS = ["question", "meta", "type", "rating_label", "rating", "selected", "qual"]


def render(family):
    section, n, expected = FAMILIES[family]

    # Inner projection: carry only archetype_id + run_id + the 7N question
    # columns into UNPIVOT. Without it all 46 persona attributes would be
    # duplicated across every one of the N output rows.
    projected = ",\n".join(
        "      " + ", ".join(f"Q{i}_{f}" for f in FIELDS) for i in range(1, n + 1)
    )

    groups = ",\n".join(
        "      ({}) AS {}".format(", ".join(f"Q{i}_{f}" for f in FIELDS), i)
        for i in range(1, n + 1)
    )

    return f"""\
-- Generated by tools/gen_unpivot.py -- do not edit by hand.
--
-- Section {section}: {n} questions per row.
-- Expected output: {expected:,} rows.

CREATE OR REPLACE TABLE `${{PROJECT_ID}}.${{DS_STG}}.stg_response_{family}` AS
SELECT
  archetype_id,
  run_id,
  q_idx,
  question_text,
  meta,
  q_type,
  rating_label,
  rating,
  selected,
  qual
FROM (
  SELECT
    archetype_id,
    -- run_id is what distinguishes the 2.1X replicate runs from the standalone
    -- 2.1 files; it must survive the unpivot.
    REGEXP_EXTRACT(_source_file, r'([^/]+)\\.csv$') AS run_id,
{projected}
  FROM `${{PROJECT_ID}}.${{DS_RAW}}.raw_read_{family}`
)
UNPIVOT (
  (question_text, meta, q_type, rating_label, rating, selected, qual)
  FOR q_idx IN (
{groups}
  )
);
"""


def main():
    args = sys.argv[1:]
    if not args:
        raise SystemExit(__doc__)

    if args[0] == "--all":
        os.makedirs("sql", exist_ok=True)
        for family in FAMILIES:
            path = os.path.join("sql", f"10_stg_response_{family}.sql")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(render(family))
            print(f"wrote {path}")
        return

    family = args[0]
    if family not in FAMILIES:
        raise SystemExit(
            f"ERROR: unknown family {family!r}; expected one of {list(FAMILIES)}"
        )
    sys.stdout.write(render(family))


if __name__ == "__main__":
    main()
