#!/usr/bin/env python3
"""
Generate sql/20_dim_archetype.sql -- one row per persona (398).

The 46 persona-attribute column names are read from the real CSV header rather
than hand-typed, because a typo in a 46-name list is easy to make and hard to
spot. Everything after those 46 columns is the normalisation layer, which is
fixed text.

Why the explicit projection matters (F1)
---------------------------------------
The plan doc's 6.1 unions raw_read_s22 and raw_read_s23 with
`SELECT * EXCEPT(_source_file, _loaded_at)`. Those tables have 291 and 298
columns, so BigQuery rejects the query outright. Projecting the 46 attributes
INSIDE each UNION arm is the fix.

All three families are unioned rather than just one, even though all 398
personas appear in every family. Persona attributes were verified
byte-identical across all 12 files, so UNION DISTINCT collapses to exactly 398
rows -- and if that ever stops being true, Gate 2 fails loudly instead of a
disagreement passing unnoticed.

Normalisation applied
---------------------
D4  age: three columns kept -- age_raw untouched, age_exact where an exact age
    is recoverable (73 personas), age_band_banner mapped to the banner buckets.
    The 22 personas whose range is '17-24' straddle two buckets and carry
    age_band_is_imputed = TRUE.
D5  gender: 'MALE' appears for one persona; INITCAP(TRIM()) folds it.
D6  income: see F6 below.
D11 nps_score is a string in source; SAFE_CAST plus a derived band.
F13 archetype_race needs normalising - see the CASE below.

Banner cut columns (race_banner, marital_banner, income_band_banner) are built
here rather than in the mart so each mapping is defined exactly once.

F6 -- income has eight shapes, not two
--------------------------------------
The doc describes only points ('$95,000 ') and ranges ('$65,000 - $75,000').
Measured over 398 personas there are eight:

    $N,N                        181     $N,N - $N,N+                  7
    $N,N - $N,N                 154     $N,N+                         2
    $N,N Household Income        33     $N,N (Household Income)       1
    $N,N (Household)             12     Household Income: $N,N        8

The doc's regex is anchored at `^\\$`, so the 8 'Household Income: $N,N'
personas get NULL income. Dropping the anchor and taking the first dollar
amount anywhere in the string handles all eight shapes with zero DQ14
violations. A '+' suffix (9 personas) is captured as income_is_open_ended
rather than being silently flattened to low = high.
"""

import csv
import os
import re
import sys

SRC_DIR = os.environ.get("SRC", "Written Descriptions_2026_08_7")
ATTR_COLS = 46
SRC_NAME_RE = re.compile(r"^3-ARENA-FF-([GS])-(gr[12])-2\.([123])(X?)")
FAMILIES = ("s21", "s22", "s23")


def attribute_names():
    """The first 46 header columns, verified identical across all 12 files."""
    headers = []
    for name in sorted(os.listdir(SRC_DIR)):
        if name.endswith(".csv") and SRC_NAME_RE.match(name[:-4]):
            with open(os.path.join(SRC_DIR, name), newline="", encoding="utf-8") as fh:
                headers.append(next(csv.reader(fh))[:ATTR_COLS])

    if len(headers) != 12:
        raise SystemExit(f"ERROR: found {len(headers)} source CSVs, expected 12")

    base = headers[0]
    for h in headers[1:]:
        if h != base:
            raise SystemExit("ERROR: persona attribute columns differ across files")
    if len(base) != ATTR_COLS:
        raise SystemExit(f"ERROR: expected {ATTR_COLS} attribute columns, got {len(base)}")
    if base[0] != "archetype_id":
        raise SystemExit(f"ERROR: first column is {base[0]!r}, expected 'archetype_id'")
    return base


def render():
    attrs = attribute_names()
    cols = ",\n".join(f"    {c}" for c in attrs)

    arms = "\n  UNION DISTINCT\n".join(
        f"  SELECT\n{cols}\n  FROM `${{PROJECT_ID}}.${{DS_RAW}}.raw_read_{fam}`"
        for fam in FAMILIES
    )

    return f"""\
-- Generated by tools/gen_dim_archetype.py -- do not edit by hand.
--
-- dim_archetype: one row per persona. Expected 398.
--
-- The 46 attributes are projected explicitly inside each UNION arm. The plan
-- doc's `SELECT * EXCEPT(...)` cannot compile here: raw_read_s22 has 291
-- columns and raw_read_s23 has 298 (F1).

CREATE OR REPLACE TABLE `${{PROJECT_ID}}.${{DS_CUR}}.dim_archetype`
CLUSTER BY creative, cohort_code AS
WITH attrs AS (
{arms}
),
parsed AS (
  SELECT
    *,
    -- exact age where recoverable: bare ages ('15') and hybrids ('21 (17-24)').
    -- Bucket forms like '25-29' correctly yield NULL.
    SAFE_CAST(
      REGEXP_EXTRACT(archetype_age_range, r'^(\\d{{1,2}})(?:\\s|$|\\s*\\()') AS INT64
    ) AS age_exact,
    -- F6: first dollar amount anywhere, not anchored at '^$'
    SAFE_CAST(
      REPLACE(REGEXP_EXTRACT(archetype_income_range, r'\\$([\\d,]+)'), ',', '') AS INT64
    ) AS income_first_usd,
    SAFE_CAST(
      REPLACE(
        REGEXP_EXTRACT(archetype_income_range, r'\\$[\\d,]+\\s*-\\s*\\$([\\d,]+)'), ',', ''
      ) AS INT64
    ) AS income_second_usd
  FROM attrs
)
SELECT
  p.*  EXCEPT(income_first_usd, income_second_usd),

  'READ' AS modality,

  CASE
    WHEN REGEXP_CONTAINS(group_name, r'-G-') THEN 'Goyer'
    WHEN REGEXP_CONTAINS(group_name, r'-S-') THEN 'Sheridan'
  END AS creative,

  CONCAT(
    CASE WHEN REGEXP_CONTAINS(group_name, r'-G-') THEN 'G' ELSE 'S' END,
    '.', REGEXP_EXTRACT(group_name, r'\\.(\\d)$')
  ) AS cohort_code,

  -- D5
  INITCAP(TRIM(archetype_gender)) AS gender_clean,

  -- D4: keep the raw value untouched alongside the derived band
  archetype_age_range AS age_raw,
  CASE
    WHEN age_exact IS NOT NULL THEN
      CASE
        WHEN age_exact <= 17 THEN '13-17'
        WHEN age_exact <= 24 THEN '18-24'
        WHEN age_exact <= 34 THEN '25-34'
        WHEN age_exact <= 44 THEN '35-44'
        WHEN age_exact <= 54 THEN '45-54'
        ELSE '55-64'
      END
    WHEN archetype_age_range = '13-16'             THEN '13-17'
    WHEN archetype_age_range = '17-24'             THEN '18-24'  -- imputed, see D4
    WHEN archetype_age_range IN ('25-29', '30-34') THEN '25-34'
    WHEN archetype_age_range IN ('35-39', '40-44') THEN '35-44'
    WHEN archetype_age_range = '45-54'             THEN '45-54'
    WHEN archetype_age_range = '55-64'             THEN '55-64'
  END AS age_band_banner,
  (archetype_age_range = '17-24') AS age_band_is_imputed,

  -- D6 / F6
  income_first_usd                              AS income_low_usd,
  COALESCE(income_second_usd, income_first_usd)  AS income_high_usd,
  REGEXP_CONTAINS(archetype_income_range, r'\\+') AS income_is_open_ended,

  -- D11
  SAFE_CAST(archetype_nps_score AS INT64) AS nps_score,
  CASE
    WHEN SAFE_CAST(archetype_nps_score AS INT64) >= 9 THEN 'Promoter'
    WHEN SAFE_CAST(archetype_nps_score AS INT64) >= 7 THEN 'Passive'
    ELSE 'Detractor'
  END AS nps_band,

  (archetype_children_status != 'no_children') AS is_parent,

  -- Banner cut columns. These live here, not in the mart, so each mapping is
  -- defined once. Target labels come from FF_READ_G_BannerPlan row 10.

  -- F13: archetype_race was carried through raw and needs normalising. Measured:
  -- 7 personas with an EMPTY value, one typo ('Latico / Hispanic'), and two
  -- spellings of the same category ('Asian or Pacific Islander' x40 vs
  -- 'Asian / Pacific Islander' x1). Unlike gender, age and income, this column
  -- had no cleaning rule until now.
  CASE
    WHEN archetype_race LIKE 'White%'                     THEN 'White Non-Hisp'
    WHEN archetype_race LIKE 'Lat%'                       THEN 'Hispanic'
    WHEN archetype_race LIKE 'Black%'                     THEN 'African American'
    WHEN archetype_race LIKE 'Asian%'                     THEN 'Asian'
    WHEN TRIM(COALESCE(archetype_race, '')) = ''          THEN 'Unknown'
    ELSE 'Other'
  END AS race_banner,

  -- The banner plan offers only SINGLE / MARRIED-PARTNERED / DIVORCED. Source
  -- has six values, so 'widowed' (12) and 'separated' (2) have no banner home.
  -- They go to OTHER rather than being dropped or forced into a category they
  -- do not belong to. The banner plan's own RELATIONSHIP rows sum to 0.978, so
  -- it has the same gap.
  CASE archetype_marital_status
    WHEN 'single'           THEN 'SINGLE'
    WHEN 'married'          THEN 'MARRIED/PARTNERED'
    WHEN 'domestic_partner' THEN 'MARRIED/PARTNERED'
    WHEN 'divorced'         THEN 'DIVORCED'
    ELSE 'OTHER'
  END AS marital_banner,

  -- Banded on the MIDPOINT of the parsed income range, the standard convention
  -- for a banded range. 13 personas would fall in a different band if banded on
  -- income_low_usd instead; that alternative is a one-line change and the
  -- affected count is asserted, so the sensitivity is measurable rather than
  -- hidden.
  CASE
    WHEN DIV(income_first_usd + COALESCE(income_second_usd, income_first_usd), 2) < 75000
      THEN '<75K'
    WHEN DIV(income_first_usd + COALESCE(income_second_usd, income_first_usd), 2) < 125000
      THEN '$75K-$125K'
    ELSE '$125K+'
  END AS income_band_banner

FROM parsed p;
"""


def main():
    if "--stdout" in sys.argv[1:]:
        sys.stdout.write(render())
        return
    os.makedirs("sql", exist_ok=True)
    path = os.path.join("sql", "20_dim_archetype.sql")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(render())
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
