-- Generated by tools/gen_unpivot.py -- do not edit by hand.
--
-- Section 1.4: 4 questions per row.
-- Expected output: 1,592 rows.

CREATE OR REPLACE TABLE `${PROJECT_ID}.${DS_STG}.stg_response_s14` AS
SELECT
  archetype_id,
  run_id,
  q_idx,
  question_text,
  meta,
  q_type,
  rating_label,
  rating,
  selected,
  qual
FROM (
  SELECT
    archetype_id,
    -- run_id is what distinguishes the 2.1X replicate runs from the standalone
    -- 2.1 files; it must survive the unpivot.
    REGEXP_EXTRACT(_source_file, r'([^/]+)\.csv$') AS run_id,
      Q1_question, Q1_meta, Q1_type, Q1_rating_label, Q1_rating, Q1_selected, Q1_qual,
      Q2_question, Q2_meta, Q2_type, Q2_rating_label, Q2_rating, Q2_selected, Q2_qual,
      Q3_question, Q3_meta, Q3_type, Q3_rating_label, Q3_rating, Q3_selected, Q3_qual,
      Q4_question, Q4_meta, Q4_type, Q4_rating_label, Q4_rating, Q4_selected, Q4_qual
  FROM `${PROJECT_ID}.${DS_RAW}.raw_read_s14`
)
UNPIVOT (
  (question_text, meta, q_type, rating_label, rating, selected, qual)
  FOR q_idx IN (
      (Q1_question, Q1_meta, Q1_type, Q1_rating_label, Q1_rating, Q1_selected, Q1_qual) AS 1,
      (Q2_question, Q2_meta, Q2_type, Q2_rating_label, Q2_rating, Q2_selected, Q2_qual) AS 2,
      (Q3_question, Q3_meta, Q3_type, Q3_rating_label, Q3_rating, Q3_selected, Q3_qual) AS 3,
      (Q4_question, Q4_meta, Q4_type, Q4_rating_label, Q4_rating, Q4_selected, Q4_qual) AS 4
  )
);
