-- Generated by tools/gen_dim_archetype.py -- do not edit by hand.
--
-- dim_archetype: one row per persona. Expected 398.
--
-- The 46 attributes are projected explicitly inside each UNION arm. The plan
-- doc's `SELECT * EXCEPT(...)` cannot compile here: raw_read_s22 has 291
-- columns and raw_read_s23 has 298 (F1).

CREATE OR REPLACE TABLE `${PROJECT_ID}.${DS_CUR}.dim_archetype`
CLUSTER BY creative, cohort_code AS
WITH attrs AS (
  SELECT
    archetype_id,
    group_name,
    sample_name,
    archetype_title,
    archetype_name,
    archetype_age_range,
    archetype_gender,
    archetype_race,
    archetype_marital_status,
    archetype_children_status,
    archetype_children,
    archetype_education_level,
    archetype_field_of_study,
    archetype_occupation,
    archetype_income_range,
    archetype_political_affiliation,
    archetype_religious_affiliation,
    archetype_location,
    archetype_location_type,
    archetype_hobbies_and_interests,
    archetype_lived_experience,
    archetype_nps_score,
    archetype_persona_summary,
    archetype_goals_and_motivations,
    archetype_audience_insights_triggers,
    archetype_psychographic_values,
    archetype_psychographic_interests,
    archetype_psychographic_lifestyle,
    archetype_purchasing_behaviors,
    archetype_challenges_pain_points,
    archetype_decision_making_steps,
    archetype_triggers_to_switch,
    archetype_product_expectations,
    archetype_product_influencers,
    archetype_media_channels,
    archetype_psychometric_vector_name,
    archetype_psychometric_vector_summary,
    archetype_psychometric_vector_characteristics,
    archetype_psychometric_vector_emotions,
    archetype_why_psychometric_vector_fits,
    archetype_group_dynamics,
    archetype_adoption_category_name,
    archetype_adoption_rationale,
    archetype_composite_attitude_score_summary,
    archetype_nps_summary,
    archetype_lived_experience_summary
  FROM `${PROJECT_ID}.${DS_RAW}.raw_read_s21`
  UNION DISTINCT
  SELECT
    archetype_id,
    group_name,
    sample_name,
    archetype_title,
    archetype_name,
    archetype_age_range,
    archetype_gender,
    archetype_race,
    archetype_marital_status,
    archetype_children_status,
    archetype_children,
    archetype_education_level,
    archetype_field_of_study,
    archetype_occupation,
    archetype_income_range,
    archetype_political_affiliation,
    archetype_religious_affiliation,
    archetype_location,
    archetype_location_type,
    archetype_hobbies_and_interests,
    archetype_lived_experience,
    archetype_nps_score,
    archetype_persona_summary,
    archetype_goals_and_motivations,
    archetype_audience_insights_triggers,
    archetype_psychographic_values,
    archetype_psychographic_interests,
    archetype_psychographic_lifestyle,
    archetype_purchasing_behaviors,
    archetype_challenges_pain_points,
    archetype_decision_making_steps,
    archetype_triggers_to_switch,
    archetype_product_expectations,
    archetype_product_influencers,
    archetype_media_channels,
    archetype_psychometric_vector_name,
    archetype_psychometric_vector_summary,
    archetype_psychometric_vector_characteristics,
    archetype_psychometric_vector_emotions,
    archetype_why_psychometric_vector_fits,
    archetype_group_dynamics,
    archetype_adoption_category_name,
    archetype_adoption_rationale,
    archetype_composite_attitude_score_summary,
    archetype_nps_summary,
    archetype_lived_experience_summary
  FROM `${PROJECT_ID}.${DS_RAW}.raw_read_s22`
  UNION DISTINCT
  SELECT
    archetype_id,
    group_name,
    sample_name,
    archetype_title,
    archetype_name,
    archetype_age_range,
    archetype_gender,
    archetype_race,
    archetype_marital_status,
    archetype_children_status,
    archetype_children,
    archetype_education_level,
    archetype_field_of_study,
    archetype_occupation,
    archetype_income_range,
    archetype_political_affiliation,
    archetype_religious_affiliation,
    archetype_location,
    archetype_location_type,
    archetype_hobbies_and_interests,
    archetype_lived_experience,
    archetype_nps_score,
    archetype_persona_summary,
    archetype_goals_and_motivations,
    archetype_audience_insights_triggers,
    archetype_psychographic_values,
    archetype_psychographic_interests,
    archetype_psychographic_lifestyle,
    archetype_purchasing_behaviors,
    archetype_challenges_pain_points,
    archetype_decision_making_steps,
    archetype_triggers_to_switch,
    archetype_product_expectations,
    archetype_product_influencers,
    archetype_media_channels,
    archetype_psychometric_vector_name,
    archetype_psychometric_vector_summary,
    archetype_psychometric_vector_characteristics,
    archetype_psychometric_vector_emotions,
    archetype_why_psychometric_vector_fits,
    archetype_group_dynamics,
    archetype_adoption_category_name,
    archetype_adoption_rationale,
    archetype_composite_attitude_score_summary,
    archetype_nps_summary,
    archetype_lived_experience_summary
  FROM `${PROJECT_ID}.${DS_RAW}.raw_read_s23`
),
parsed AS (
  SELECT
    *,
    -- exact age where recoverable: bare ages ('15') and hybrids ('21 (17-24)').
    -- Bucket forms like '25-29' correctly yield NULL.
    SAFE_CAST(
      REGEXP_EXTRACT(archetype_age_range, r'^(\d{1,2})(?:\s|$|\s*\()') AS INT64
    ) AS age_exact,
    -- F6: first dollar amount anywhere, not anchored at '^$'
    SAFE_CAST(
      REPLACE(REGEXP_EXTRACT(archetype_income_range, r'\$([\d,]+)'), ',', '') AS INT64
    ) AS income_first_usd,
    SAFE_CAST(
      REPLACE(
        REGEXP_EXTRACT(archetype_income_range, r'\$[\d,]+\s*-\s*\$([\d,]+)'), ',', ''
      ) AS INT64
    ) AS income_second_usd
  FROM attrs
)
SELECT
  p.*  EXCEPT(income_first_usd, income_second_usd),

  'READ' AS modality,

  CASE
    WHEN REGEXP_CONTAINS(group_name, r'-G-') THEN 'Goyer'
    WHEN REGEXP_CONTAINS(group_name, r'-S-') THEN 'Sheridan'
  END AS creative,

  CONCAT(
    CASE WHEN REGEXP_CONTAINS(group_name, r'-G-') THEN 'G' ELSE 'S' END,
    '.', REGEXP_EXTRACT(group_name, r'\.(\d)$')
  ) AS cohort_code,

  -- D5
  INITCAP(TRIM(archetype_gender)) AS gender_clean,

  -- D4: keep the raw value untouched alongside the derived band
  archetype_age_range AS age_raw,
  CASE
    WHEN age_exact IS NOT NULL THEN
      CASE
        WHEN age_exact <= 17 THEN '13-17'
        WHEN age_exact <= 24 THEN '18-24'
        WHEN age_exact <= 34 THEN '25-34'
        WHEN age_exact <= 44 THEN '35-44'
        WHEN age_exact <= 54 THEN '45-54'
        ELSE '55-64'
      END
    WHEN archetype_age_range = '13-16'             THEN '13-17'
    WHEN archetype_age_range = '17-24'             THEN '18-24'  -- imputed, see D4
    WHEN archetype_age_range IN ('25-29', '30-34') THEN '25-34'
    WHEN archetype_age_range IN ('35-39', '40-44') THEN '35-44'
    WHEN archetype_age_range = '45-54'             THEN '45-54'
    WHEN archetype_age_range = '55-64'             THEN '55-64'
  END AS age_band_banner,
  (archetype_age_range = '17-24') AS age_band_is_imputed,

  -- D6 / F6
  income_first_usd                              AS income_low_usd,
  COALESCE(income_second_usd, income_first_usd)  AS income_high_usd,
  REGEXP_CONTAINS(archetype_income_range, r'\+') AS income_is_open_ended,

  -- D11
  SAFE_CAST(archetype_nps_score AS INT64) AS nps_score,
  CASE
    WHEN SAFE_CAST(archetype_nps_score AS INT64) >= 9 THEN 'Promoter'
    WHEN SAFE_CAST(archetype_nps_score AS INT64) >= 7 THEN 'Passive'
    ELSE 'Detractor'
  END AS nps_band,

  (archetype_children_status != 'no_children') AS is_parent

FROM parsed p;
